name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  MISE_EXPERIMENTAL: true

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
        with:
          version: 2026.8.6
      - run: mise install --locked
      - run: mise run ci
